### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by emanuele45** [Wedge/tools#4]
Notice: Undefined variable: in_comment in /Globye.php on line 218 found in a foreach

**Comment by Nao** [comment]
This version of Globye.php is totally not working.
Please checkout the December 30 version, or one from early January. This should work.

I'm currently working on committing the latest version, the one that I finally managed to get to work earlier today. (It has a lot of changes.)

**Comment by Nao** [comment]
Done! (Still, note that this version is of no interest for Elk, as you guys don't have PHP 5.3+, so you might want to work with the old one instead. You can also use both; they might find different results, although I doubt it..!)
